# Generated by Django 5.2.8 on 2025-11-15 20:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_rename_title_project_name'),
        ('votes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'project')},
        ),
    ]
