# Generated by Django 5.2.8 on 2025-11-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
