# Generated by Django 5.2.8 on 2025-11-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
    ]
